### ISSUE TITLE
Well done

### ISSUE THREAD

**Issue by secdim** [siraj-mx51/secdim-assessment#2]
Well done Siraj, patch looked really good. Your submission was complete.

One area of improvement, choice of security weakness made it hard to write a security test using Go's testing framework. It is better to use other tools such as gitleak to search for hardcoded credentials in the code or repository. This case you can keep tests identical in both main and master branch.

Great work.

**Comment by siraj-mx51** [comment]
Thanks for your feedback and the recommendation about `gitleak`. Will definitely check it out.
